services:
  vector-api:
    build: .
    ports:
      - "${API_PORT}:${API_PORT}"

  milvus-db:
    image: milvusdb/milvus:latest
    ports:
      - "19530:19530"
      - "19121:19121"
    environment:
      - MILVUS_DB_PATH=${MILVUS_DB_PATH}
